General:
  lang: "language.yml"
Connection:
  host: 192.168.99.100
  port: 3306
  database: gmctest
  user: root
  password: gmc
  tablePrefix: GCS_
Interfaces:
  background: '160:15'
  newEnchere: '399:0'