# ========================= File config.yml =========================
#
# Version : 1.14
#
# This file contains all config for GlobalMarketChest plugin
#
# ===================================================================

General:
  # Possible values : lang-fr_FR.yml and lang-en_EN.yml
  Lang: "lang-en_EN.yml"
Connection:
  # The url/ip to access to your database server
  Host: localhost
  # Port used by your database server
  Port: 3306
  # The database name that you have already created
  Database: my_database
  # The user you want to use to login
  User: my_user
  # The password of the user set above
  Password: my_password
  # The prefix you want to user of tables to avoid conflicts with other tables
  TablePrefix: GMC_
  # The simultaneous connection always active to reduce time of interface execution
  SimultaneousConnection: 4
Options:
  # To see auctions that don't have category
  UncategorizedItems: false
  # Define if the button MaxInOne in CreateAuction view must be here
  EnableMaxInOne: true
  # Define if the button MaxRepeat in CreateAuction view must be here
  EnableMaxRepeat: true
  # Define if a player can find similar auctions with drag and drop on category view 
  EnableSimilarAuctions: true
  # Default price for new auctions
  DefaultPrice: 100
  # Use the price of the last similar auction as price of new auction
  UseLastPrice: true
  # Define the maximum auctions by player
  MaxAuctionByPlayer : 50
  # Broadcast a message inside the current world when a player buy an auction
  BroadcastInsideWorld: true
  # Notify the player everywhere on the server when a player buy one of his auctions
  NotifyPlayer: true
  # An auction expire if it is older than NumberDaysExpiration
  NumberDaysExpiration: 7
  # -1 to ignore purge else specific a number of days to purge database every n days
  # NOT YET SUPPORTED
  PurgeInterval: 30
  # Define if the player can create auctions with an item damaged
  AcceptDamagedItems: false
Logs:
  # If set to true the prefix [GlobalMarketChest] inside messages will be removed
  HidePrefix: false
# Worlds on which you can create shop
WorldAllowed:
  - world
  - world_the_end
  - world_nether
# Block that you can link with shop's sign
AllowedLinkBlock:
  - minecraft:ender_chest
  - minecraft:chest
Price:
  # Define if the button "Free" must be place dynamically at the end of the line or at a fixed position
  DynamicFreePosition: true
  # All price ranges value, you can have maximum 9 ranges (chest width)
  Ranges:
    - 1000
    - 100
    - 10
    - 1
    - 0.1
    - 0.01
  # Items used for price ranges, if there is less items than price ranges the last item 
  Items:
    - minecraft:emerald_block
    - minecraft:emerald
    - minecraft:diamond_block
    - minecraft:diamond
    - minecraft:gold_ingot
    - minecraft:iron_ingot
    - minecraft:coal
    - minecraft:redstone
    - minecraft:lapis_lazuli
# Items that can't be sold
ItemsBlacklist:
  - minecraft:barrier
  - minecraft:chain_command_block
  - minecraft:command_block
  - minecraft:command_block_minecart
  - minecraft:debug_stick
  - minecraft:knowledge_book
  - minecraft:repeating_command_block
  - minecraft:structure_block
  - minecraft:structure_void
  - minecraft:jigsaw
  - minecraft:suspicious_stew
Interfaces:
  # Warning interface messages are represented by flashing item alternating Background this item
  Warn: minecraft:red_stained_glass_pane
  # All others buttons used inside interface are defined here
  Buttons:
    Background: minecraft:black_stained_glass_pane
    NewAuction: minecraft:nether_star
    CreateAuction: minecraft:nether_star
    BuyAuction: minecraft:nether_star
    RenewAuction: minecraft:orange_wool
    UndoAuction: minecraft:red_wool
    RenewEveryAuction: minecraft:orange_wool
    UndoEveryAuction: minecraft:red_wool
    ExitButton: minecraft:barrier
    Validate: minecraft:spectral_arrow
    Return: minecraft:tipped_arrow
    CreateShop: minecraft:nether_star
    Money: minecraft:gold_ingot
    GlobalView: minecraft:enchanted_book
    Search: minecraft:hopper
    SearchItemDrop: minecraft:grass_block
    SearchItemText: minecraft:paper
    SearchByPlayer: minecraft:player_head
    ViewByCategory: minecraft:compass
    ViewByPlayer: minecraft:chest
    ViewByLastCreated: minecraft:apple
    AuctionSide: minecraft:blue_stained_glass_pane
    AuctionMiddle: minecraft:stained_glass_pane
    GlobalShop: minecraft:ender_chest
    AuctionShop: minecraft:shulker_box
    AdminShop: minecraft:chest
    ShopIcon: minecraft:ender_chest
    EditGroupName: minecraft:blue_stained_glass_pane
    PreviousPage: minecraft:arrow
    NextPage: minecraft:arrow
    NumPage: minecraft:book
    MaxInOne: minecraft:orange_stained_glass_pane
    MaxRepeat: minecraft:orange_stained_glass_pane
    InProgressAuction: minecraft:book
    ExpiredAuction: minecraft:book
    SoldAuction: minecraft:book
    BoughtAuction: minecraft:book
    CanceledAuction: minecraft:book
    FreePrice: minecraft:lime_stained_glass_pane
    CircleSetItem: "minecraft:lime_stained_glass_pane"
    CircleUnsetItem: "minecraft:blue_stained_glass_pane"
    YesButton: "minecraft:lime_wool"
    NoButton: "minecraft:red_wool"
    Question: "minecraft:redstone_torch"
Sign:
  Appearance:
    # Config for GobalShop creation
    GlobalShop:
      # The text displayed on the sign when shop creation is successful
      DisplayName: "&a[GlobalShop]"
      # The item used inside the shop as icon
      DisplayItem: minecraft:compass
      # The first line that must write on sign to create shop
      FirstLineToCreate: "globalshop"
    # The text displayed on the sign when shop creation failed
    NotWorkingShopDisplayName : "&c[DisableShop]"
